server {
    listen 80;
    server_name _;

    client_max_body_size 300m;
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    location = / {
        return 302 /drugreflector/;
    }

    location ^~ /drugreflector/ {
        alias /usr/share/nginx/html/drugreflector/;
        try_files $uri $uri/ /drugreflector/index.html;
    }

    location ^~ /drugreflector-api/ {
        proxy_pass http://api:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
